version: '3'
services:
  nodejs: 
    build: ./
    image: tiotobing/nodejs
    restart: unless-stopped
    container_name: community-solid-server
  nginx: 
    build: ./nginx
    image: tiotobing/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/data:/etc/letsencrypt
      - ./certbot/data/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx